# Generated by Django 6.0.2 on 2026-09-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_alter_role_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpage',
            name='image_credit',
            field=models.CharField(blank=True, help_text='Name the photographer, organization, or other image source.', max_length=255, verbose_name='Image credit'),
        ),
        migrations.AddField(
            model_name='branchpage',
            name='image_credit_url',
            field=models.URLField(blank=True, help_text='Optional link to the original image or source.', verbose_name='Image source URL'),
        ),
    ]
