# Generated by Django 6.0.2 on 2026-09-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_althomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image_credit',
            field=models.CharField(blank=True, help_text='Name the photographer, organization, or other image source.', max_length=255, verbose_name='Hero image credit'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_credit_url',
            field=models.URLField(blank=True, help_text='Optional link to the original image or source.', verbose_name='Hero image source URL'),
        ),
    ]
